# DB Configuration :
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Web Server (Tomcat) configuration :
server.port=8082
server.servlet.context-path=/tpfoyer

# Actuator endpoints
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# Metrics related configurations
management.endpoint.metrics.enabled=true
management.endpoint.prometheus.enabled=true